### PR TITLE
Update App layers

### PR DESCRIPTION
**Pull request by ZigaMahne**
- use fixed ARM.mbedTLS 1.7.0 pack

Reference projects will be synchronized in future update

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by KeilChris** [comment]
Patch looks ok. Pins Mbed TLS to v1.7.0.

**Comment by acabarbaye** [comment]
If the solution for the problem is to fix the dependency version of the packs used by the examples, I would also pin down the version of the other packs (e.g. Paho_MQTT), at least to the major number, as this problem may happen again as soon as a dependency configuration changes. As a side note, shouldn't mbedTLS pack version of the pack with additional configuration be incremented to the next major version number as this seems to be a breaking change (i.e. the upgrade to that version makes the build no longer possible).

**Pull request merged**
